### ISSUE TITLE
Middleman blog

### ISSUE THREAD

**Issue by ljuboja** [clearsightstudio/middleman-template#3]
Is this template compatible with middleman blog, what is the best way to include blog  with this nice template? Tnx

**Comment by yulianglukhenko** [comment]
Hi ljuboja! Thank you for the interest in our version of the middleman template. 

I don't think we made any changes to the template in any way that would prevent default blog usage; therefore, there shouldn't be any specific setup instructions. Just follow the instructions found on this page: https://middlemanapp.com/basics/blogging/ 

Here's an example from our http://clearsightstudio.com website.

Add `gem "middleman-blog"` to the Gemfile

In the config.rb:

```
Time.zone = "America/Los_Angeles"

activate :blog do |blog|
  blog.prefix = "blog"
  blog.permalink = ":year/:month/:day/:title.html"
  blog.sources = "posts/:year-:month-:day-:title.html"
  blog.taglink = "tags/:tag.html"
  blog.layout = "blog_layout"
  blog.summary_separator = /(KEEPREADING)/
  blog.summary_length = 500
  blog.default_extension = ".slim"
  blog.tag_template = "/blog/tag.html"
  blog.paginate = true
  blog.per_page = 3
  blog.page_link = "page-:num"
end

page "blog/feed.xml", layout: false
```

Create directories / files:

```
/source/layouts/blog_layout.html.slim
/source/blog/posts/*
/source/blog/tag.html.slim
/source/blog/feed.xml.builder (https://gist.github.com/yulianglukhenko/d7bc61a20c7eac169764)
```

I hope this points you in the right direction. Let me know if you have more questions.
